### ISSUE TITLE
Export to HTML in Auto-Layout

### ISSUE THREAD

**Issue by lucasgonze** [AnimaApp/docs#1]
It's not clear from the docs whether it's possible to export to HTML we host ourselves. Is there a method?

Somewhere in the documentation this should be addressed, even if only as a FAQ saying it is not supported.

**Comment by orarbel** [comment]
Thanks!

We will add this to the docs but in the mean time: https://medium.com/sketch-app-sources/how-to-export-sketch-to-html-65c427b3aa3a
