### ISSUE TITLE
It doesn't work 

### ISSUE THREAD

**Issue by marcello77** [AnimaApp/docs#2]
Hi,
once installed the plugin doesn't work even if it's present in the plugin list, in other words any command as Show/Hide Panel or Generate overview doesn't work.
I've just installed the plugin or via Sketch Toolbox or copying it into the plugin's folder, but as I said no way to work!

Can you help me, please?
The plugin is great, I'd like to use it.

I'm on Sketch 41.2, OSX 10.10.5

Thank you in advance.

![schermata 2017-02-18 alle 20 39 18](https://cloud.githubusercontent.com/assets/15831723/23096327/79231d66-f61a-11e6-82ae-f8d6124a8650.png)

**Comment by orarbel** [comment]
Hi there, for Yosemite the link is http://animaapp.s3.amazonaws.com/sketchplugin/autolayout/older/AutoLayoutPlugin%20-%200.1.2%20MultipleSelection.zip

**Comment by orarbel** [comment]
Added Yosmite link to installation page

**Comment by marcello77** [comment]
Now it works!
Thank you so much.
