### ISSUE TITLE
Images in docs won't display in Chrome

### ISSUE THREAD

**Issue by aparajita** [AnimaApp/docs#29]
Chrome 72.0.3626.121 is refusing to display images from `/f.cl.ly` because:

```
This server could not prove that it is f.cl.ly; its security certificate is from *.s3.amazonaws.com
```

So most of the embedded images in the docs are not displayed. Am I the only one who is seeing this?

**Comment by orarbel** [comment]
Can you share a link to a page with a broken image please?

**Comment by aparajita** [comment]
Any page on https://docs.animaapp.com 

Chrome itself just issues a warning in the console. In my case Ghostery is blocking the images — and it's doing the right thing, because you've got a bad cert.
