### ISSUE TITLE
Stop working on Sketch 52.4

### ISSUE THREAD

**Issue by najandz** [AnimaApp/docs#5]
Stop working on the latest sketch app 52.4, can you please let us know when we can have it back.

Thank you,

**Comment by orarbel** [comment]
It seems to be working for us and many of the users. Can you elaborate on the issue?

**Comment by najandz** [comment]
Hi Or,

Thanks for the quick reply, the error message was 'it is not compatible with version 53.4', after I toggle the plugin it works,

Cheers,
